trigger:
  branches:
    include:
      - main

variables:
  vmImage: 'ubuntu-latest'

stages:
  - stage: build_stage
    jobs:
      - job: build
        pool:
          vmImage: $(vmImage)
        steps:
          - script: echo "hello emmanuel"
            displayName: 'Print greeting'